name: Chore/Infrastructure
description: Tasks related to maintenance, infrastructure, DevOps, or technical debt
title: "[CHORE] "
labels: ["chore", "infrastructure"]
body:
  - type: markdown
    attributes:
      value: |
        Report maintenance tasks, infrastructure work, or technical improvements.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of work is this?
      options:
        - Infrastructure/DevOps
        - Database Maintenance
        - Dependencies/Updates
        - Code Refactoring
        - Technical Debt
        - Performance Optimization
        - Security Updates
        - Build/CI/CD
        - Configuration
        - Monitoring/Logging
        - Testing Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/System
      description: Which part of the system is affected?
      options:
        - Backend API
        - Frontend
        - Database
        - AWS Infrastructure
        - Nginx/Reverse Proxy
        - CAD Sessions (OnShape/KiCAD)
        - Proctoring Service
        - Scoring Service
        - Email Service
        - S3/Storage
        - Authentication
        - CI/CD Pipeline
        - Monitoring/Alerts
        - Multiple Components
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the maintenance task or infrastructure work needed
      placeholder: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this work needed? What problem does it solve?
      placeholder: |
        - Reason 1
        - Reason 2
        - Impact if not done
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope of Work
      description: What specific tasks need to be completed?
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this work?
      options:
        - Critical (Security/Production down)
        - High (Performance impact/Blocking)
        - Medium (Should do soon)
        - Low (Nice to have/Can wait)
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: Rough estimate of work required
      options:
        - Small (< 2 hours)
        - Medium (2-8 hours)
        - Large (1-3 days)
        - Extra Large (> 3 days)

  - type: textarea
    id: risks
    attributes:
      label: Risks/Considerations
      description: Any risks or important considerations?
      placeholder: |
        - Potential downtime
        - Breaking changes
        - Dependencies
        - Rollback plan

  - type: textarea
    id: testing
    attributes:
      label: Testing/Verification
      description: How will this work be verified?
      placeholder: |
        - How to test the changes
        - Success criteria
        - Rollback procedure

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Related issues, PRs, documentation, etc.

