name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this affect?
      options:
        - scoring
        - assessment-platform
        - database
        - proctoring
        - email
        - user.colare.com
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Need
      description: What problem does this feature solve? What need does it address?
      placeholder: "As a [user type], I need [feature] because [reason]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe how you envision this feature working
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocks major functionality)
        - High (Significantly improves user experience)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, diagrams, or examples
      placeholder: Drag and drop images or describe examples

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Related features, technical considerations, etc.

