name: Question
description: Ask a question about the codebase or system
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - Architecture/Design
        - Implementation/Code
        - Setup/Configuration
        - Deployment
        - Database
        - API Usage
        - Frontend
        - CAD Sessions
        - Proctoring/Scoring
        - Authentication/Security
        - Performance
        - Testing
        - General
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you already tried? What documentation have you checked?
      placeholder: |
        - Checked: docs/...
        - Tried: ...
        - Related code: ...

  - type: textarea
    id: goal
    attributes:
      label: What Are You Trying to Achieve?
      description: Understanding your goal helps us provide better answers
      placeholder: Describe what you're working on or trying to accomplish

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any code snippets, screenshots, or other helpful information
      placeholder: Provide any additional context

